// newsReact/src/App.jsx
import { useState } from 'react'

import PostData from "./components/PostData.jsx";
import PostList from "./components/PostList.jsx";
import FavoriteList from "./components/FavoriteList.jsx";

function App(props) {

    const commentList = props.comments;
    const postList = props.posts;
    const [postData, setPostData] = useState(postList[0])
    const [commentData, setCommentData] = useState(commentList[0])
    const [favorite, setFavorite] = useState([])
    const [listType, setListType] = useState(0)

    const updatePostData = (event) => {
        const postId = event.target.dataset["id"]
        const commentIndex = commentList.findIndex(c => {return c.postId == postId})
        const commentId = commentList[commentIndex]['id']
//        console.log("postId = %d, commentId = %d", postId, commentId)
//        console.log(event.target.dataset["id"])
//        console.log(event.target.getAttribute("data-id"))

        setPostData(postList[postId])
        setCommentData(commentList[commentId])
    }

    const addFavorite = (event) => {
        setFavorite([...favorite, parseInt(event.target.dataset['id'])])
    }

    const listDefinition = [
        <PostList postList={postList} handleClick={updatePostData} />,
        <FavoriteList favorite={postList.filter(post => {return favorite.includes(post['id'])})} />
    ]

    const changeType = (event) => {
        setListType(listType === 0 ? 1 : 0)
    }


    return (
        <div className="wrap">
            <div className="left">
                <div>
                    <input type="checkbox" onClick={changeType} />
                </div>
                {listDefinition[listType]}
            </div>
            <div className="right">
                <PostData postData={postData} commentData={commentData}
                          addFavorite={addFavorite}
                />
            </div>
        </div>
    )
}

export default App

// newsVue/src/App.vue
<script setup>
import {ref, reactive, toRefs} from 'vue'

import Comments from "./data/Comments.js";
import Posts from "./data/Posts.js";

import PostListComponent from "./components/PostListComponent.vue"
import PostDataComponent from "./components/PostDataComponent.vue"
import FavoriteListComponent from "./components/FavoriteListComponent.vue";

const commentList = Comments;
const postList = Posts;
const favoriteList = ref({});

let PostData = ref(postList[0]);
let CommentData = ref(commentList[0]);
let favorite = ref([]);
let listType = ref(0);

const handleClick = (post) => {
    const postId = post.id
    const commentIndex = commentList.findIndex(c => {return c.postId == postId})
    const commentId = commentList[commentIndex]['id']
//        console.log("postId = %d, commentId = %d", postId, commentId)
//        console.log(event.target.dataset["id"])
//        console.log(event.target.getAttribute("data-id"))

    PostData.value = postList[postId]
    CommentData.value = commentList[commentId]
}

const addFavorite = (id) => {
    favorite.value.push(id)
    favoriteList.value = postList.filter(post => {return favorite.value.includes(post['id'])})
}

const changeType = (event) => {
    listType.value = listType.value == 0 ? 1 : 0
}
</script>

<template>
    <div class="wrap">
        <div class="left">
            <div>
                <input type="checkbox" @click="changeType" />
            </div>
            <div v-if="listType == 0">
                <PostListComponent :postList=postList @handleClick=handleClick />
            </div>
            <div v-else>
                <FavoriteListComponent :postList=favoriteList />
            </div>
        </div>
        <div class="right">
            <PostDataComponent
                :postData=PostData
                :commentData=CommentData
                @addFavorite=addFavorite
            />
        </div>
    </div>
</template>

<style scoped>
.wrap {
    display: flex;
    justify-content: space-between;
    width: 1000px;
}

.left {
    width: 300px;
    border: 1px solid #ccc;
    border-radius: 10px;
}

.right {
    width: 600px;
}
.post {
    border: 1px solid #ccc;
    border-radius: 10px;
    padding: 20px;
}
</style>
