// newsReact/src/components/FavoriteList.jsx
import React, {useState} from "react";

const FavoriteList = (props) => {
    const [searchText, setSearchText] = useState("")

    const handleChange = (event) => {
        setSearchText(event.target.value)
    }

    return (
        <>
            <div className="inputWrap">
                <input type="text" placeholder="search" onChange={handleChange} />
            </div>
            <ul>
                {
                    props.favorite.filter(p => {return searchText.length == 0 || p.title.indexOf(searchText) >= 0}).map(p =>
                        <li key={p.id} data-id={p.id} onClick={props.handleClick}>{p.title}</li>
                    )
                }
            </ul>
        </>
    )
}

export default FavoriteList

// newsVue/src/components/FavoriteListComponent.vue
<script setup>

/**
 * props
 * @type {Readonly<{[key in string]?: any}>}
 */
const props = defineProps([
    'postList'
])

</script>

<template>
    <div>
        <div class="inputWrap">
            <input type="text" placeholder="search" onChange="handleChange" />
        </div>
        <ul>
            <li v-for="post in props.postList" v-bind:key="post.id" class="post-data">
                <span @click="emit('handleClick', post)">{{ post.title }}</span>
            </li>
        </ul>
    </div>
</template>

<style scoped>
</style>
